server:
  port: 8080
spring:
  datasource:
    username: postgres
    password: pass
    url: jdbc:postgresql://localhost:5432/web
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    open-in-view: false
